name: Replace README

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test'
        required: false
  issue_comment:
    types: [created, edited]

env:
  GITHUB_NAME: GeorgeCh2
  GITHUB_EMAIL: georgechmr@gmail.com

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Replace README
        run: |
          source venv/bin/activate
          python main.py ${{ secrets.G_T }} ${{ github.repository }} --issue_numbe '${{ github.event.issue.number }}' --issue_label_name '${{ github.event.issue.labels[0].name }}' 

      - name: Run safe dir
        run: |
          git config --global --add safe.directory /github/workspace
          
      - name: Push new README
        run: |
          git config --local user.name georgechou
          git config --local user.email georgechmr@gmail.com
          git add .
          git commit -m "generated readme" || echo "no need to commit "
          git push || echo "no file change"
